# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BIzY0JxU2lh5PZJiYy3RAXQZk52vXMdO
"""

print("select an operation to perform")
print("1. ADDITION")
print("2. SUBTRACT")
print("3. MULTIPLY")
print("4. DIVIDE")
print("5. EXIT")

operation = input("Enter a Number: ")


if operation == "1":
    num1 = input("enter first number: ")
    num2 = input("enter second number: ")
    print("the sum is " + str(int(num1) + int(num2)))
elif operation == "2":
      num1 = input("enter first number: ")
      num2 = input("enter second number: ")
      print("the sum is " + str(int(num1) - int(num2)))
elif operation == "3":
      num1 = input("enter first number: ")
      num2 = input("enter second number: ")
      print("the sum is " + str(int(num1) * int(num2)))
elif operation == "4":
      num1 = input("enter first number: ")
      num2 = input("enter second number: ")
      print("the sum is " + str(int(num1) / int(num2)))

else:
    print("Invalid Entry")

x = input("Enter a character :")
x = x.lower()
if(x=='a' or x=='e' or x=='i' or x=='o' or x=='u'):
    print("It is a vowel")
else:
    print("It is a constant")

def convert_temperature():

    print("Choose the conversion:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")
    choice = input("Enter 1 or 2: ")

    if choice == '1':
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius} Celsius is equal to {fahrenheit:.2f} Fahrenheit.")
    elif choice == '2':
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit} Fahrenheit is equal to {celsius:.2f} Celsius.")
    else:
        print("Invalid choice. Please enter 1 or 2.")
convert_temperature()

x=int(input("Enter A Number 1. :"))
y=int(input("Enter A Number 2. :"))
z=int(input("Enter A Number 3. :"))
if (x>=y) and (x>=z):
     largest=x
elif (y>=x) and z(y>=z):
     largest=y
else:
    largest=z
print("The largest number is",largest)

Amount = int(input("Enter sale price: "))
if(Amount>0):
    if Amount >=100:
        dis = Amount*0.10
    elif Amount <100:
        dis = Amount*0.05
    print("discount :",dis)
    print("net pay : ",Amount-dis)
else:
    print("invalid Amount")